### PR TITLE
[bugfix] only calls job.onComplete if defined and adds res as an argument.

### PR DESCRIPTION
**Pull request by agchou**
Fixed bugs where onComplete was being called each time a job was triggered and where onComplete was being called without passing in the response.

### CODE REVIEW

**Review by antonsamper — APPROVED** [review]

**Review by antonsamper — CHANGES_REQUESTED** [review]
@agchou can you add test where `onComplete` is not a function?

**Comment by antonsamper** [comment]
Dont worry about the test, i'll merge it in and quickly add it on my side. Thanks for the PR.

**Comment by antonsamper** [comment]
This PR will close #8

**Review by antonsamper — APPROVED** [review]

**Comment by agchou** [comment]
Just saw this. Thanks @antonsamper!

**Pull request merged**
